set nocompatible
call pathogen#infect()
syntax on
set smartindent
set shiftwidth=4
set softtabstop=4
set expandtab
set number
set statusline=%{fugitive#statusline()}
set laststatus=2
set backspace=indent,eol,start
